name: Update Image

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:  

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create images directory
      run: mkdir -p images

    - name: Download image
      run: |
        curl -o images/stats.png https://www.destroydevs.ru/api/stats

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add images/stats.png
        git commit -m "Update stats image"
        git push
