name: Update Image

on:
  schedule:
    - cron: '* * * * *'  
  workflow_dispatch:  

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Remove old image
      run: rm -f images/stats.png

    - name: Download image
      run: |
        curl -o images/stats.png https://www.destroydevs.ru/api/stats

    - name: Check if image was downloaded
      run: |
        if [ -f images/stats.png ]; then
          echo "Image downloaded successfully"
        else
          echo "Image download failed"
          exit 1
        fi

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add images/stats.png
        git commit -m "Update stats image"
        git push
